import {Urbanist} from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

const urbanist = Urbanist({
    variable: "--font-urbanist",
    subsets: ["latin"],
});



export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",

};

export default function RootLayout({children}) {
    return (
        <html
            lang="en"

        >
        <body className={`${urbanist.variable} h-full antialiased`}>

        <Header/>
        {children}</body>
        </html>
    );
}
